### ISSUE TITLE
Migrate docsify to MkDocs

### ISSUE THREAD

**Issue by proddy** [emsesp/docs#29]
Planning to migrate this docsify generated markup over wiki to MkDocs (https://www.mkdocs.org/) using the Material UI theme (https://squidfunk.github.io/mkdocs-material/). It looks nicer, search is faster and I'm able to sort on tables which is needed for https://github.com/emsesp/EMS-ESP32/issues/828

**Comment by proddy** [comment]
done. URL is the same https://emsesp.github.io/docs/

@MichaelDvP let me know what you think.

**Comment by MichaelDvP** [comment]
Nice, looks more clear. The supported device list is the one wthout thermostat hc-model-specific entities. Wait for the heatsource device before creating the new, looks like a lot of work.

**Comment by proddy** [comment]
it was one of those things that I thought i could do in <1hr but as always I think spent a whole night doing it. it wasn't fun.
