### ISSUE TITLE
Formatting of `Special functions`

### ISSUE THREAD

**Issue by MichaelDvP** [emsesp/docs#34]
The `Remote thermostats` section show odd in the wiki, but i can't see why, in editor preview all is ok.
Preview:
![grafik](https://github.com/emsesp/docs/assets/59284019/7265206e-0f06-46a1-8722-9523891a4dfd)
Wiki:
![grafik](https://github.com/emsesp/docs/assets/59284019/bd9c1efb-c5c1-4fc0-8ca1-aa5b117175b2)

**Comment by proddy** [comment]
I'll fix

**Comment by proddy** [comment]
fixed.
